/* ════════════════════════════════════════════════════════
   GrahAI — Daily Push Notification Cron Job

   Runs every hour (checks which timezones are at sunrise ~6 AM)
   and sends personalized daily cosmic guidance push notifications
   to subscribed users in those timezones.

   Uses the daily_insights data generated by the daily-insights cron
   job (which runs at 6:00 AM IST = 00:30 UTC).

   Vercel cron config (vercel.json):
   { "path": "/api/cron/daily-push", "schedule": "0 * * * *" }

   Sunrise window: 5:30 AM - 6:30 AM local time
   ════════════════════════════════════════════════════════ */

import { NextRequest, NextResponse } from "next/server"
import { createClient } from "@supabase/supabase-js"
import { sendBatchPush, getSupabaseAdmin } from "@/lib/push/sender"
import {
  createDailyPushContent,
  getGenericDailyContent,
} from "@/lib/push/content-templates"

// ─── Config ────────────────────────────────────────────

const SUNRISE_WINDOW_START = 5.5 // 5:30 AM
const SUNRISE_WINDOW_END = 6.5 // 6:30 AM

// ─── Cron Auth ────────────────────────────────────────

function verifyCronAuth(req: NextRequest): boolean {
  const authHeader = req.headers.get("authorization")
  const cronSecret = process.env.CRON_SECRET

  if (cronSecret) {
    return authHeader === `Bearer ${cronSecret}`
  }

  // Vercel cron fallback
  const vercelCron = req.headers.get("x-vercel-cron")
  if (vercelCron === "true" && process.env.VERCEL === "1") return true

  return false
}

// ─── Get Timezones That Are At Sunrise Right Now ────────

function getTimezoneOffsetHours(tz: string): number {
  // Simple mapping of common Indian and international timezones
  // Proper implementation would use Intl.DateTimeFormat or date-fns
  const tzMap: Record<string, number> = {
    "Asia/Kolkata": 5.5,
    "Asia/Calcutta": 5.5,
    "IST": 5.5,
    "Asia/Bangalore": 5.5,
    "Asia/Bombay": 5.5,
    "Asia/Delhi": 5.5,
    "Asia/Dhaka": 6,
    "Asia/Bangkok": 7,
    "Asia/Singapore": 8,
    "Asia/Hong_Kong": 8,
    "Asia/Tokyo": 9,
    "UTC": 0,
    "GMT": 0,
    "Europe/London": 0,
    "Europe/Paris": 1,
    "Europe/Berlin": 1,
    "America/New_York": -5,
    "America/Los_Angeles": -8,
    "America/Chicago": -6,
    "America/Denver": -7,
    "Australia/Sydney": 10,
    "Pacific/Auckland": 12,
  }

  return tzMap[tz] ?? 5.5 // Default to IST
}

function isTimezoneAtSunrise(tz: string): boolean {
  const offset = getTimezoneOffsetHours(tz)
  const utcNow = new Date()

  // Calculate local time in that timezone
  const localHours = (utcNow.getUTCHours() + offset) % 24

  // Check if local time is in sunrise window (5:30 - 6:30 AM)
  return localHours >= SUNRISE_WINDOW_START && localHours < SUNRISE_WINDOW_END
}

// ─── GET Handler (Vercel Cron) ────────────────────────

export async function GET(req: NextRequest) {
  const startTime = Date.now()

  // Verify cron auth
  if (!verifyCronAuth(req)) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
  }

  const supabase = getSupabaseAdmin()
  const today = new Date().toISOString().split("T")[0]

  let processed = 0
  let sent = 0
  let failed = 0
  let skipped = 0
  const errors: Array<{ userId: string; error: string }> = []

  try {
    // Get all push subscriptions with user info
    const { data: subscriptions, error: fetchError } = await supabase
      .from("push_subscriptions")
      .select(
        `
        id,
        user_id,
        endpoint,
        keys,
        timezone,
        profiles!inner (
          id,
          email
        )
      `
      )

    if (fetchError) {
      console.error("Fetch subscriptions error:", fetchError)
      return NextResponse.json(
        { error: "Failed to fetch subscriptions", details: String(fetchError) },
        { status: 500 }
      )
    }

    if (!subscriptions || subscriptions.length === 0) {
      return NextResponse.json({
        success: true,
        date: today,
        processed: 0,
        sent: 0,
        failed: 0,
        skipped: 0,
        reason: "No push subscriptions found",
        durationMs: Date.now() - startTime,
      })
    }

    // Filter subscriptions by timezone (only send to sunrise timezones)
    const eligibleSubs = subscriptions.filter((sub) =>
      isTimezoneAtSunrise(sub.timezone || "Asia/Kolkata")
    )

    if (eligibleSubs.length === 0) {
      return NextResponse.json({
        success: true,
        date: today,
        processed: subscriptions.length,
        sent: 0,
        failed: 0,
        skipped: subscriptions.length,
        reason: "No subscriptions in sunrise window",
        durationMs: Date.now() - startTime,
      })
    }

    // For each eligible user, get their daily insight and send push
    const subsToSend = []

    for (const sub of eligibleSubs) {
      processed++

      try {
        // Get user's daily insight for today
        const { data: insight, error: insightError } = await supabase
          .from("daily_insights")
          .select("*")
          .eq("user_id", sub.user_id)
          .eq("date", today)
          .single()

        if (insightError && insightError.code !== "PGRST116") {
          // PGRST116 = not found (which is fine)
          console.error(
            `Error fetching insight for user ${sub.user_id}:`,
            insightError
          )
          errors.push({
            userId: sub.user_id,
            error: `Insight fetch error: ${insightError.message}`,
          })
          failed++
          continue
        }

        let pushContent

        if (insight) {
          // Use personalized insight
          pushContent = createDailyPushContent(insight, "Friend")
        } else {
          // No insight available, use generic message
          pushContent = getGenericDailyContent("Friend")
        }

        subsToSend.push({
          ...sub,
          pushContent,
        })
      } catch (err) {
        console.error(`Error processing subscription ${sub.user_id}:`, err)
        errors.push({
          userId: sub.user_id,
          error: String(err),
        })
        failed++
      }
    }

    // Send all collected notifications in batch
    if (subsToSend.length > 0) {
      // Get the push content (all should be the same for daily push)
      const pushContent = subsToSend[0].pushContent

      // Prepare subscription objects for web-push
      const webPushSubs = subsToSend.map((sub) => ({
        endpoint: sub.endpoint,
        keys: sub.keys,
        user_id: sub.user_id,
      }))

      // Send batch
      const result = await sendBatchPush(webPushSubs, {
        title: pushContent.title,
        body: pushContent.body,
        url: pushContent.url,
        tag: pushContent.tag,
      })

      sent = result.sent
      failed += result.failed

      if (result.errors.length > 0) {
        errors.push(
          ...result.errors.map((err) => ({
            userId: "unknown",
            error: `${err.endpoint}: ${err.error}`,
          }))
        )
      }
    }

    // Log cron execution
    try {
      await supabase.from("cron_logs").insert({
        job_name: "daily_push",
        date: today,
        processed,
        emailed: sent, // Use emailed column for sent count
        errors: failed,
        duration_ms: Date.now() - startTime,
      })
    } catch (logErr) {
      console.error("Cron log insert error:", logErr)
    }

    return NextResponse.json({
      success: true,
      date: today,
      processed,
      sent,
      failed,
      skipped,
      eligibleCount: eligibleSubs.length,
      errors:
        errors.length > 0
          ? errors.slice(0, 10)
          : "No errors",
      durationMs: Date.now() - startTime,
    })
  } catch (error) {
    console.error("Daily push cron fatal error:", error)
    return NextResponse.json(
      {
        error: "Cron job failed",
        details: String(error),
      },
      { status: 500 }
    )
  }
}
